import { chromium, expect } from "@playwright/test";
import { mkdir, writeFile } from "node:fs/promises";
import assert from "node:assert/strict";
import { toggleService, budgetLabel, buildBrief, USD_BUDGETS, PKR_BUDGETS } from "../src/lib/projectBrief.ts";
assert.deepEqual(toggleService(["seo"],"nfc-cards"),["seo","nfc-cards"]);
assert.deepEqual(toggleService(["seo","nfc-cards"],"seo"),["nfc-cards"]);
assert.equal(budgetLabel("PKR",3),"Rs. 100,000+");
assert.equal(budgetLabel("USD",3),"More than $10,000");
await mkdir("artifacts/qa",{recursive:true});
const browser=await chromium.launch({channel:"chrome",headless:true,args:["--no-proxy-server"]});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:"reduce"});
const page=await context.newPage();
const errors=[];page.on("pageerror",error=>errors.push(error.message));
const reports=[];
let requestBody="",responseCode=503,requestCount=0;
await page.route("https://ntfy.sh/contact-devops",async route=>{requestCount++;requestBody=route.request().postData()||"";await route.fulfill({status:responseCode,contentType:"application/json",body:responseCode===200?'{"id":"test-mocked"}':'{"error":"simulated"}'});});
try{
 await page.goto("http://127.0.0.1:4173",{waitUntil:"domcontentloaded"});
 await expect(page.locator("h1")).toBeVisible();
 await page.locator(".studio-service").filter({has:page.getByRole("heading",{name:"SEO Solutions",exact:true})}).getByRole("button").click();
 await page.locator("#contact").scrollIntoViewIfNeeded();
 await expect(page.getByRole("checkbox",{name:"SEO Solutions",exact:true})).toBeChecked();
 await page.getByRole("checkbox",{name:"NFC Card Services",exact:true}).check();
 await expect(page.locator('input[name="services"]:checked')).toHaveCount(2);
 const budget=page.locator('select[name="budget"]');
 assert.deepEqual((await budget.locator("option").allTextContents()).slice(1),USD_BUDGETS);
 await budget.selectOption("2");
 await page.getByRole("radio",{name:"Rs. PKR"}).check();
 await expect(budget).toHaveValue("");
 assert.deepEqual((await budget.locator("option").allTextContents()).slice(1),PKR_BUDGETS);
 await budget.selectOption("3");
 reports.push("USD ranges preserved; PKR 35k–100k+ ranges correct; changing currency resets budget; services remain selected.");
 await page.locator(".language-select select").selectOption("FR");
 await expect(page.locator("html")).toHaveAttribute("lang","fr");
 await expect(page.locator('input[name="services"]:checked')).toHaveCount(2);
 await expect(budget).toHaveValue("3");
 await page.reload({waitUntil:"domcontentloaded"});
 await expect(page.locator(".language-select select")).toHaveValue("FR");
 await page.locator(".language-select select").selectOption("DE");
 await expect(page.locator("h1")).toContainText("VORSPRUNG.");
 await page.locator(".language-select select").selectOption("JP");
 await expect(page.locator("html")).toHaveAttribute("lang","ja");
 await page.locator(".language-select select").selectOption("EN");
 reports.push("All four languages switch; language persists on reload; service and budget selection survive language changes.");
 await page.locator("#contact").scrollIntoViewIfNeeded();
 await page.locator('input[name="fullName"]').fill("Test Client");
 await page.locator('input[name="email"]').fill("test@example.com");
 await page.locator('input[name="companyName"]').fill("Test Studio");
 await page.locator('select[name="country"]').selectOption("Pakistan");
 await page.locator('select[name="industry"]').selectOption({index:1});
 await page.locator('textarea[name="description"]').fill("TEST ONLY — browser test with mocked delivery. Website, SEO and NFC cards.");
 await page.getByRole("radio",{name:"Rs. PKR"}).check();
 await budget.selectOption("0");
 await page.getByRole("button",{name:"Send project brief",exact:true}).click();
 await expect(page.locator("#service-error")).toBeVisible();
 assert.equal(requestCount,0);
 await page.getByRole("checkbox",{name:"Website Development",exact:true}).check();
 await page.getByRole("checkbox",{name:"NFC Card Services",exact:true}).check();
 await page.getByRole("button",{name:"Send project brief",exact:true}).click();
 await expect(page.locator(".form-error")).toContainText("couldn't send");
 await expect(page.locator('input[name="fullName"]')).toHaveValue("Test Client");
 assert.match(requestBody,/Website Development, NFC Card Services/);
 assert.match(requestBody,/Preferred payment currency: PKR/);
 assert.match(requestBody,/Rs\. 35,000 - 50,000/);
 responseCode=200;
 await page.getByRole("button",{name:"Send project brief",exact:true}).click();
 await expect(page.locator(".brief-success")).toBeVisible();
 await expect(page.locator(".brief-success")).toContainText("NFC Card Services");
 await expect(page.locator(".brief-success")).toContainText("PKR");
 reports.push("Required service validation prevents sending; mocked failure preserves input; mocked retry succeeds with all services, currency and budget.");
 await page.getByRole("button",{name:"Start another brief"}).click();
 await expect(page.locator('input[name="services"]:checked')).toHaveCount(0);
 await expect(page.locator('input[name="fullName"]')).toHaveValue("");
 await page.goto("http://127.0.0.1:4173/case-studies/babey-dee-atta-chakki",{waitUntil:"domcontentloaded"});
 await expect(page.getByRole("heading",{name:"Babay Dee Atta Chakki",exact:true})).toBeVisible();
 const images=await page.locator("article img").evaluateAll(nodes=>nodes.map(n=>({src:n.getAttribute("src"),loaded:n.complete&&n.naturalWidth>0})));
 assert(images.some(x=>x.src?.includes("User%20attachment")||x.src?.includes("User attachment")));
 await page.screenshot({path:"artifacts/qa/case-study.png"});
 await page.goto("http://127.0.0.1:4173/case-studies",{waitUntil:"domcontentloaded"});
 await expect(page.locator("h1")).toBeVisible();
 reports.push("Case study detail and directory routes render with the supplied Babay Dee screenshots.");
 await page.setViewportSize({width:390,height:844});
 await page.goto("http://127.0.0.1:4173",{waitUntil:"domcontentloaded"});
 await page.getByRole("button",{name:"Open navigation"}).click();
 await expect(page.locator("#mobile-navigation")).toBeVisible();
 await page.keyboard.press("Escape");
 await expect(page.locator("#mobile-navigation")).toHaveCount(0);
 const overflows=[];
 for(const lang of ["EN","FR","DE","JP"]){
  await page.locator(".language-select select").selectOption(lang);
  const result=await page.evaluate(()=>({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));
  if(result.scroll>result.width+1)overflows.push({lang,...result});
 }
 assert.deepEqual(overflows,[]);
 reports.push("Mobile menu opens and closes with Escape; no horizontal document overflow in all four languages.");
 assert.deepEqual(errors,[]);
 reports.push("No browser JavaScript errors.");
 await writeFile("artifacts/qa/interactions.json",JSON.stringify({passed:true,reports,errors,requestCount,delivery:"All submissions intercepted locally; no real messages sent."},null,2));
 console.log(JSON.stringify({passed:true,reports},null,2));
}finally{await browser.close();}
